# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "/"
title = "FinTech Insights"
# theme = "congo"  # Commented out for Hugo modules
defaultContentLanguage = "en"

# Language configuration
[languages]
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    weight = 1
  [languages.vi]
    languageCode = "vi-VN"
    languageName = "Tiếng Việt"
    weight = 2

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true
