languageCode = "en-US"
languageName = "English (United States)"
languageDirection = "ltr"
weight = 1

title = "FinTech Insights"
copyright = "&copy; 2024 Tam Le"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["posts"]
  description = "Personal research notebook documenting investment strategies and trading approaches discovered through AI-assisted and manual research."

[params.author]
  name = "Tam Le"
  image = "img/author.jpg"
  headline = "Investment Research & Trading Strategies"
  bio = "Documenting my research journey exploring investment and trading approaches through AI-assisted discovery and manual research. Passionate about value investing, quantitative finance, and behavioral markets."
  links = [
    { linkedin = "https://linkedin.com/in/tamlefpa" },
  ]
