languageCode = "vi-VN"
languageName = "Tiếng Việt"
languageDirection = "ltr"
weight = 2

title = "FinTech Insights"
copyright = "&copy; 2024 Tam Le"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["posts"]
  description = "Sổ tay nghiên cứu cá nhân ghi chép các chiến lược đầu tư và phương pháp giao dịch được khám phá qua nghiên cứu có hỗ trợ AI."

[params.author]
  name = "Tam Le"
  image = "img/author.jpg"
  headline = "Nghiên cứu đầu tư & Chiến lược giao dịch"
  bio = "Ghi chép hành trình nghiên cứu của tôi về các phương pháp đầu tư và giao dịch thông qua nghiên cứu có hỗ trợ AI và tìm kiếm thủ công. Đam mê đầu tư giá trị, tài chính định lượng và tâm lý thị trường."
  links = [
    { linkedin = "https://linkedin.com/in/tamlefpa" },
  ]
