languageCode = "en-US"
languageName = "English (United States)"
languageDirection = "ltr"
weight = 1

title = "FinTech Insights"
copyright = "&copy; 2024 FinTech Insights"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["posts"]
  description = "Exploring the latest trends, technologies, and insights in financial technology."

[params.author]
  name = "FinTech Insights Team"
  image = "img/author.jpg"
  headline = "Your guide to financial technology!"
  bio = "We are passionate about exploring the intersection of finance and technology, bringing you the latest insights, trends, and analysis in the FinTech world."
  links = [
    { x-twitter = "https://twitter.com/" },
    { facebook = "https://facebook.com/" },
    { linkedin = "https://linkedin.com/" },
    { youtube = "https://youtube.com/" },
  ]
