languageCode = "vi-VN"
languageName = "Tiếng Việt"
languageDirection = "ltr"
weight = 2

title = "FinTech Insights"
copyright = "&copy; 2024 FinTech Insights"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["posts"]
  description = "Khám phá những xu hướng, công nghệ và thông tin mới nhất trong lĩnh vực công nghệ tài chính."

[params.author]
  name = "Đội ngũ FinTech Insights"
  image = "img/author.jpg"
  headline = "Hướng dẫn bạn về công nghệ tài chính!"
  bio = "Chúng tôi đam mê khám phá sự giao thoa giữa tài chính và công nghệ, mang đến cho bạn những thông tin, xu hướng và phân tích mới nhất trong thế giới FinTech."
  links = [
    { x-twitter = "https://twitter.com/" },
    { facebook = "https://facebook.com/" },
    { linkedin = "https://linkedin.com/" },
    { youtube = "https://youtube.com/" },
  ]
